In [5]:
from calvin_utils.plotting_utils.date_symptom_plot import SymptomProgressionPlotter
plotter = SymptomProgressionPlotter(
        json_path="/Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper/json_evaluated/emr_strict_extraction_evaluations_mapped.json",  # must have symptoms for a patients response from review pyper
        onset_csv_path="/Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper_severity/master_list_2_w_dummy_onset.csv", # must have an onset date to register to
        symptoms=["oes this patient have difficulty walking or disturbed gait?"], # This is a list of the JSON keys to extract symptoms from
        output_dir="/Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper/plots",    
        onset_col="dummy_onset",        # From the CSV, determines 'onset' to lock each patient's trace to
        drop_unknown=True,              # This removes 'unknown' from showing up on the plot
        unknown_value=0,                # Value given to unknowns. Default is -1, but will probably be 0 for binary questions
        time_range=(-18,12), # Time window (in months) before and after onset to show 
        value_range=(0,2), # Range of y-axis values to display
        transition_threshold_months=3,  # This deteremines within how many months from onset we consider the onset causing the symptom change        
        coerce_observation_threshold=0,
    )

plotter.run()
plotter.export_csv()

Resolved symptom substring to JSON key:
  oes this patient have difficulty walking or disturbed gait?
  -> Does this patient have difficulty walking or disturbed gait? For instance, they may mention the patient staggering, difficulties in half turn, requiring support from a wall or stick, or being entirely unable to walk on their own. If the text does not mention walking or gait, or only mentions gait changes caused by pain or injury, respond "not mentioned"

Plot saved to /Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper/plots/DateSymptomPlot_Does_this_patient_have_difficu.html
Patient conditions exported to /Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper/plots/PatientConditions_Does_this_patient_have_diffic.csv

,MRN,Symptom,Condition
0,00000017,Does this patient have difficulty walking or d...,YES BEFORE ONSET | NO AFTER ONSET

In [6]:
from calvin_utils.plotting_utils.date_symptom_plot import SymptomProgressionPlotter
plotter = SymptomProgressionPlotter(
        json_path="/Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper_severity/json_evaluated/emr_strict_extraction_evaluations_2_mapped.json",  # must have symptoms for a patients response from review pyper
        onset_csv_path="/Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper_severity/master_list_2_w_dummy_onset.csv", # must have an onset date to register to
        symptoms=["Which of these most closely describes the patient's gait?"], # This is a list of the JSON keys to extract symptoms from
        output_dir="/Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper_severity/plots",    
        onset_col="dummy_onset",        # From the CSV, determines 'onset' to lock each patient's trace to
        drop_unknown=True,              # This removes 'unknown' from showing up on the plot
        unknown_value=-1,                # Value given to unknowns. Default is -1, but will probably be 0 for binary questions
        time_range=(-18,12), # Time window (in months) before and after onset to show 
        value_range=(-1,8), # Range of y-axis values to display
        transition_threshold_months=3,  # This deteremines within how many months from onset we consider the onset causing the symptom change        
        coerce_observation_threshold=0,
    )

plotter.run()
plotter.export_csv()

Resolved symptom substring to JSON key:
  Which of these most closely describes the patient's gait?
  -> Which of these most closely describes the patient's gait? If the text does not mention walking or gait, or only mentions gait changes caused by pain or injury, respond "-1" -1: No information about the patient's gait provided. 0: Normal. 1: Almost normal naturally, but unable to walk with feet in tandem position. 2: Walking without support, but clearly abnormal and irregular. 3: Walking without support but with considerable staggering; difficulties in half turn. 4: Walking without support not possible; uses support of the wall for 10-meter test. 5: Walking possible only with one cane. 6: Walking possible only with two canes or with a stroller. 7: Walking possible only with one accompanying person. 8: Walking impossible with one accompanying person (2-person assist; wheelchair)

Plot saved to /Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper_severity/plots/DateSymptomPlot_Which_of_these_most_closely_de.html
Patient conditions exported to /Users/rm026/Documents/code/ReviewPyper_testing/tests/custommapper_severity/plots/PatientConditions_Which_of_these_most_closely_d.csv

,MRN,Symptom,Condition
0,00000017,Which of these most closely describes the pati...,YES BEFORE ONSET | YES AFTER ONSET